name: cube
description: A Multi Wallet.

publish_to: 'none'

version: 1.1.2+112

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  firebase_crashlytics: ^2.2.3

  flustars: ^2.0.1
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.6
  flutter_spinkit: ^5.0.0
  flutter_easyloading: ^3.0.0
  flutter_easyrefresh: ^2.2.1
  flutter_card_swipper: ^0.4.0
  persistent_bottom_nav_bar: ^4.0.2
  extended_nested_scroll_view: ^3.0.0
  pull_to_refresh_notification: ^2.0.1
  loading_more_list: ^4.0.0

  dio: ^4.0.0
  path: ^1.8.0
  lottie: ^1.0.1
  logger: ^1.0.0
  decimal: ^1.3.0
  crypto: ^3.0.1
  event_bus: ^1.1.0
  open_file: ^3.2.1
  provider: ^5.0.0
  sqflite: ^2.0.0+3
  qr_flutter: ^4.0.0
  device_info: ^2.0.0
  share_extend: ^2.0.0
  path_provider: ^2.0.2
  barcode_scan2: ^4.1.4
  r_scan: ^0.1.6+1
  package_info: ^2.0.2
  sticky_headers: ^0.2.0
  shared_preferences: ^2.0.5
  permission_handler: ^8.0.1
  local_auth: ^0.6.3+4
  url_launcher: ^5.2.7
  connectivity_plus: ^1.0.4
  umeng_common_sdk: 1.1.3
  cached_network_image: ^3.0.0

  get:
    path: plugins/getx
  jpush_flutter:
    path: plugins/jpush-flutter-plugin
  webview_flutter:
    path: plugins/webview_flutter-2.0.12
  webview_flutter_plus:
    path: plugins/webview_flutter_plus-0.2.2
  bee_encryption:
    path: plugins/bee_encryption


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
